name = "medbill-auditor"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "MEDBILL_KV"
id = "d14f596fc0e94cdab95f6c26bdf31b28"

[[r2_buckets]]
binding = "BILLS_BUCKET"
bucket_name = "medbill-bills"

[vars]
SITE_URL = "https://medbill-auditor.pages.dev"
CONTACT_EMAIL = "support@medbill.ai"
SCAN_EMAIL = "scan@medbill.ai"
ENVIRONMENT = "production"
